# Use root/example as user/password credentials
services:
  db:
    container_name: 10.11.11-jammy
    image: mariadb:10.11.11-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
    - 3308:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    container_name: adminer-5.2.1-standalone
    image: adminer:5.2.1-standalone
    restart: always
    ports:
    - 9080:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - 9081:80
      # Change the number before : to the port the SMTP server should be accessible on
      - 9025:25
